### ISSUE TITLE
Copy Writing Proposal

### ISSUE THREAD

**Issue by Gallantmayor** [funeralzone/MsgPackPhp#1]
Hello, i just checked your lovely project and i discovered you have some sections missing out like FAQ, about us, contact us and privacy policy. If you dont mind i will like to write that for you.
My email: gallantmayor22@gmail.com

**Comment by decebal** [comment]
thank you for the suggestion @Gallantmayor, these are not really needed for this kind of project, certainly not for what we have in mind for it.
